### ISSUE TITLE
Floppy drive motor kept on during game play.

### ISSUE THREAD

**Issue by dougmasten** [nowhereman999/Joust_CoCo3#2]
I'm using MAME and after loading the floppy drive motor sound is still on during game play. It never shuts off. If I am in debug mode I can shut if off by poking 0 to $ff40.

**Comment by nowhereman999** [comment]
Hi Doug,

Thanks for finding the drive motor always on bug and letting me know how to fix it.  I’ve attached V1.1 which does a CLR $FF40 just before the game starts.  Please give it a test.

I also added you and Einar Saukas in the Please_Read_This.txt to thank you properly for the ZX0 code rather then just on my blog, it should have been included in V1.0

Please feel free to email directly ***@***.*** ***@***.***> anytime.

Speaking of which, do you think you can send me a copy of the drive motor and any other sounds that mame can use while emulating the CoCo?

Thanks again,
Glen

**Comment by dougmasten** [comment]
Hey Glen, 

I just tested V1.1 and it solves the issue with the drive motor. So thank you.

Also thanks for the mention. I'm glad someone was able to make use of it.

And here's MAME sound sample if this is what you need. 
https://github.com/mamedev/mame/tree/master/samples/floppy

Doug Masten
